# Stage 1
FROM node:20 as builder

WORKDIR /arcube/client

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

# Stage 2
FROM nginx:stable


WORKDIR /usr/share/nginx/html

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /arcube/client/build .

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
